version: '3.3'
services:
  app:
    container_name: notification_service
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3010:3010'
    command: npm start
    environment:
      - NODE_ENV=development
