version: '3.3'
services:
  app:
    container_name: notification_service
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3010:3010'
    environment:
      - NODE_ENV=production
    command: node build/app.js
