version: '3.3'
services:
  app:
    container_name: notification_service
    build: .
    volumes:
      - /usr/app/node_modules
    environment:
      - TWILIO_SID
      - TWILIO_TOKEN
    ports:
      - '3010:3010'
