version: '3.3'
services:
  app:
    container_name: notification_service
    build: .
    volumes:
      - /usr/app/node_modules
    environment:
      - TWILIO_SID
      - TWILIO_TOKEN
      - TWILIO_NUMBER
      - MAIL_MAIL
      - MAIL_PASSWORD
      - DB_DATABASE
      - DB_HOST
      - DB_PASSWORD
      - DB_USER
    ports:
      - '3010:3010'
